services:
  spring-app:
    image: 160885265705.dkr.ecr.ap-northeast-2.amazonaws.com/ktb-samsam-be-ecr:latest
    container_name: spring-app
    ports:
      - "8090:8090"
    volumes:
      - ./logs:/app/logs