input {
  tcp {
    port => 5044
    codec => json_lines
  }

  file {
    path => "/app/logs/*.log"
    start_position => "beginning"
    sincedb_path =>"/dev/null"
  }
}

filter {
  grok {
    match => { "message" => "%{TIMESTAMP_ISO8601:timestamp} %{LOGLEVEL:loglevel} %{GREEDYDATA:restOfMessage}" }
  }

  date {
    match => ["timestamp", "YYYY-MM-dd HH:mm:ss"]
  }

  if [message] =~ /^\s*$/ {
    drop {}
  }
}


output {
  stdout { codec => rubydebug }
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "spring-logs-%{+YYYY.MM.dd}"
  }
}
